apiVersion: v1
kind: Pod
metadata:
  name: nginx   # pod name
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  containers:
  - name: nginx # containers name
    image: nginx  # by default it iwll get from docker hub4
